node-id = 2
[redis]
redis-port = 6380
tls-port = 6480
# 全局统一 redis 哨兵的 master 名字
sentinel-master-name = "cat"
# 在没有请求到来时，多少秒进行一次 key 的清理，0 表示不清理
cleaning-interval = 100
databases = 16
# requirepass = "123"
[raft]
address = "127.0.0.1:5002"
log-path = "C:/tmp/raft/cache-cat/2"
single = false
join = ["127.0.0.1:5001"]
advertise-host = "127.0.0.1"
# 选举超时时间，节点之间的时钟偏移不能超过该值，需要大于 500
election-timeout = 799
# 超过这个值将会直接进行快照，为 0 代表不用快照
snapshot-policy = 5000000
# 超过这个阈值表示严重落后，主节点会将快照发给从节点，而不是增量同步。需要大于 snapshot-policy，防止快照还没生成。
replication-lag-threshold = 500000000
[tls]
tls-cert-file = "C:/tmp/openssl/redis.crt"
tls-key-file = "C:/tmp/openssl/redis.key"
tls-ca-cert-file = "C:/tmp/openssl/ca.crt"
# 是否要求客户端开启验证
tls-auth-clients = false
tls-protocols = "TLSv1.2 TLSv1.3"
tls-replication = true