node_id = 3
redis_addr = "127.0.0.1:6381"

#在没有请求到来时 多少秒进行一次key的清理 0表示不清理
cleaning_interval = 100
databases = 16
[raft]
address = "127.0.0.1:5003"
advertise_host = "127.0.0.1"
single = false
join = ["127.0.0.1:5001"]

log_path = "C:/tmp/raft/cache-cat/3"


#选举超时时间，节点之间的时钟偏移不能超过该值 需要大于500
election_timeout = 799
#超过这个值将会直接进行快照，为0代表用不快照
snapshot_policy = 50000
#超过这个阈值表示严重落后，主节点会将快照发给从节点，而不是增量同步。需要大于snapshot_policy,防止快照还没生成。
replication_lag_threshold = 60000

